### ISSUE TITLE
Unable to authenticate with configuration server

### ISSUE THREAD

**Issue by robscully** [marcosbarbero/spring-cloud-config-client-oauth2#1]
Hello Macros,

I have a configuration server with oauth2 security enabled running in front of vault and consul. I have been trying with your project to authenticate via JHipster UAA. I have created a basic project from start.spring.io to test and included your project in it. This is my pom.xml

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.new.app</groupId>
	<artifactId>oauth2client</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>oauth2client</name>
	<description>Demo project for Spring Boot</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.4.2.RELEASE</version>
		<relativePath/> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.marcosbarbero.cloud</groupId>
			<artifactId>spring-cloud-config-client-oauth2</artifactId>
			<version>1.0.1.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-config</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-oauth2</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-consul-discovery</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>Camden.SR2</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
`

The following is my main application class:
`
@SpringBootApplication
@EnableOAuth2Client
@EnableAutoConfiguration
@EnableDiscoveryClient
public class Oauth2clientApplication {

	public static void main(String[] args) {
		SpringApplication.run(Oauth2clientApplication.class, args);
	}
}
`

And this is my bootstrap.xml

`spring:
  application:
    name: myservice
  profiles:
    active: default
    consul:
      config:
        enabled: true
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        acl-token: thistoken
  cloud:
    config:
      client:
        enabled: true
        oauth2:
          clientId: internal
          client-id: internal
          client-secret: internal
          access-token-uri: http://localhost:9999/oauth/token
          scope:
            - trusted-client
          grant-type: client_credentials
          userAuthorizationUri: http://localhost:9999/oauth/authorize
          resource:
            jwt:
              key-uri: http://localhost:9999/oauth/token_key
      uri: http://localhost:8080
      fail-fast: true
server:
  port: 8081`

When I run my client to get the configuration from my configuration server, I get the following:

`2016-11-11 09:57:44.160  INFO 5905 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:8080
2016-11-11 09:57:45.266  INFO 5905 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:8080
2016-11-11 09:57:46.410  INFO 5905 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:8080
2016-11-11 09:57:47.663  INFO 5905 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:8080
2016-11-11 09:57:49.071  INFO 5905 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:8080
2016-11-11 09:57:50.590  INFO 5905 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:8080
2016-11-11 09:57:50.629  WARN 5905 --- [           main] o.s.boot.SpringApplication               : Error handling failed (ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@716a7124: startup date [Thu Jan 01 01:00:00 GMT 1970]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@26d9b808)
2016-11-11 09:57:50.637 ERROR 5905 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Could not locate PropertySource and the fail fast property is set, failing
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:130) ~[spring-cloud-config-client-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$$FastClassBySpringCGLIB$$fa44b2a.invoke(<generated>) ~[spring-cloud-config-client-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720) ~[spring-aop-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:74) ~[spring-retry-1.1.4.RELEASE.jar:na]
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:276) ~[spring-retry-1.1.4.RELEASE.jar:na]
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:157) ~[spring-retry-1.1.4.RELEASE.jar:na]
	at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:101) ~[spring-retry-1.1.4.RELEASE.jar:na]
	at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:119) ~[spring-retry-1.1.4.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655) ~[spring-aop-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$$EnhancerBySpringCGLIB$$8a8340c3.locate(<generated>) ~[spring-cloud-config-client-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:89) ~[spring-cloud-context-1.1.5.RELEASE.jar:1.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:635) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:349) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at com.new.app.Oauth2clientApplication.main(Oauth2clientApplication.java:26) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147) [idea_rt.jar:na]
Caused by: org.springframework.web.client.HttpClientErrorException: 401 null
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:667) ~[spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:620) ~[spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:580) ~[spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:498) ~[spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.getRemoteEnvironment(ConfigServicePropertySourceLocator.java:170) ~[spring-cloud-config-client-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:91) ~[spring-cloud-config-client-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	... 24 common frames omitted
`

Am I doing something wrong in my configuration here or are some modifications required for new Spring Cloud releases?

Thanks,
Rob.

**Comment by robscully** [comment]
Update:

I've modified my POM as some dependencies were interfering with your project. This is my new basic POM:

`
    <modelVersion>4.0.0</modelVersion>

```
<groupId>com.new.app</groupId>
<artifactId>oauth2client</artifactId>
<version>0.0.1-SNAPSHOT</version>
<packaging>jar</packaging>

<name>oauth2client</name>
<description>Demo project for Spring Boot</description>

<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.4.2.RELEASE</version>
    <relativePath/> <!-- lookup parent from repository -->
</parent>

<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <java.version>1.8</java.version>
</properties>

<dependencies>
    <dependency>
        <groupId>com.marcosbarbero.cloud</groupId>
        <artifactId>spring-cloud-config-client-oauth2</artifactId>
        <version>1.0.1.RELEASE</version>
    </dependency>

    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter</artifactId>
    </dependency>


    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-test</artifactId>
        <scope>test</scope>
    </dependency>
</dependencies>

<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>Camden.SR2</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>

<build>
    <plugins>
        <plugin>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
        </plugin>
    </plugins>
</build>
```

</project>
`

From there I get the following stack trace:

---

APPLICATION FAILED TO START

---

Description:

Field resourceDetails in com.marcosbarbero.cloud.config.oauth2.ConfigClientOAuth2BootstrapConfiguration$ConfigClientOAuth2Configurer required a single bean, but 2 were found:
    - configClientOAuth2ResourceDetails: defined by method 'configClientOAuth2ResourceDetails' in com.marcosbarbero.cloud.config.oauth2.ConfigClientOAuth2BootstrapConfiguration
    - spring.cloud.config.client-com.marcosbarbero.cloud.config.oauth2.ConfigClientOAuth2ResourceDetails: defined in null

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed

2016-11-11 10:30:02.810  WARN 8225 --- [           main] o.s.boot.SpringApplication               : Error handling failed (no error message)
2016-11-11 10:30:02.827 ERROR 8225 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'configClientOAuth2Configurator': Unsatisfied dependency expressed through field 'resourceDetails'; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'com.marcosbarbero.cloud.config.oauth2.ConfigClientOAuth2ResourceDetails' available: expected single matching bean but found 2: configClientOAuth2ResourceDetails,spring.cloud.config.client-com.marcosbarbero.cloud.config.oauth2.ConfigClientOAuth2ResourceDetails
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:592) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
    at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:370) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1219) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:754) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
    at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) ~[spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
    at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:138) ~[spring-cloud-context-1.1.5.RELEASE.jar:1.1.5.RELEASE]
    at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:84) ~[spring-cloud-context-1.1.5.RELEASE.jar:1.1.5.RELEASE]
    at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:62) ~[spring-cloud-context-1.1.5.RELEASE.jar:1.1.5.RELEASE]
    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
    at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:68) ~[spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
    at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54) ~[spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
    at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:337) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
    at com.new.app.Oauth2clientApplication.main(Oauth2clientApplication.java:20) [classes/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147) [idea_rt.jar:na]
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'com.marcosbarbero.cloud.config.oauth2.ConfigClientOAuth2ResourceDetails' available: expected single matching bean but found 2: configClientOAuth2ResourceDetails,spring.cloud.config.client-com.marcosbarbero.cloud.config.oauth2.ConfigClientOAuth2ResourceDetails
    at org.springframework.beans.factory.config.DependencyDescriptor.resolveNotUnique(DependencyDescriptor.java:172) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1109) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:589) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
    ... 34 common frames omitted

Process finished with exit code 1

It appears that we're finding two beans of types:

configClientOAuth2ResourceDetails,spring.cloud.config.client-com.marcosbarbero.cloud.config.oauth2.ConfigClientOAuth2ResourceDetails

and are conflicting. Any ideas on how I could fix this?

Thanks,
Rob.

**Comment by marcosbarbero** [comment]
Hello there! Sorry for this delay to reply you and thanks for using my code and helping to improve it I really appreciate that!

Unfortunately I can't take a deep look até your issue because I'm out of computer and moving country. If you find the issue and it's in my project you can provide a pull request, if you can wait once I've a computer I'll look into it for sure.

**Comment by robscully** [comment]
Thanks Macros. Will have a look at it and see what we can do. I'll update once we have a solution.

**Comment by robscully** [comment]
Hi Marcos, The following fixes the issues:

```
@Configuration
@EnableOAuth2Client
@EnableConfigurationProperties(ConfigClientOAuth2ResourceDetails.class)
@ConditionalOnClass({ConfigServicePropertySourceLocator.class, OAuth2RestTemplate.class})
@ConditionalOnProperty(value = ConfigClientOAuth2ResourceDetails.PREFIX + ".oauth2.client-id")
public class ConfigClientOAuth2BootstrapConfiguration  {

   @Autowired
   private ConfigurableEnvironment environment;

   @Bean
   @Primary
   @ConditionalOnMissingBean(ConfigClientOAuth2ResourceDetails.class)
   public ConfigClientOAuth2ResourceDetails configClientOAuth2ResourceDetails() {
       return new ConfigClientOAuth2ResourceDetails();
   }

   @Bean
   @Primary
   public ConfigClientProperties configClientProperties() {
       ConfigClientProperties client = new ConfigClientProperties(this.environment);
       client.setEnabled(true);
       return client;
   }

   @Bean
   @Primary
   @ConditionalOnProperty(value = "spring.cloud.config.enabled", matchIfMissing = true)
   protected ConfigClientOAuth2Configurer configClientOAuth2Configurator(ConfigServicePropertySourceLocator configServicePropertySourceLocator,
                                                                         ConfigClientOAuth2ResourceDetails configClientOAuth2ResourceDetails) {
       return new ConfigClientOAuth2Configurer(configServicePropertySourceLocator, configClientOAuth2ResourceDetails);
   }

   protected static class ConfigClientOAuth2Configurer {

   private final ConfigServicePropertySourceLocator locator;

   private final ConfigClientOAuth2ResourceDetails configClientOAuth2ResourceDetails;

   public ConfigClientOAuth2Configurer(ConfigServicePropertySourceLocator locator,
                                       ConfigClientOAuth2ResourceDetails configClientOAuth2ResourceDetails) {
       this.locator = locator;
       this.configClientOAuth2ResourceDetails = configClientOAuth2ResourceDetails;
   }

   @PostConstruct
   public void init() {
       this.locator.setRestTemplate(new OAuth2RestTemplate(this.configClientOAuth2ResourceDetails.getOauth2()));
   }

   }
}
```

Sorry about the formatting, it doesn't appear to be working well for me.

Thanks,
Rob.

**Comment by marcosbarbero** [comment]
Hi @robscully I'm back to the track! I'll take a look into that issue later today and delivery a new version once everything is fixed! Thanks for your patience.

**Comment by marcosbarbero** [comment]
@robscully tell me, is this piece really needed?

```
@Bean
    @Primary
    public ConfigClientProperties configClientProperties(ConfigurableEnvironment environment) {
        ConfigClientProperties client = new ConfigClientProperties(environment);
        client.setEnabled(true);
        return client;
    }
```

I'm asking it because the default value is `true`, I'll make a new release updating the version of `spring-cloud-config`

**Comment by marcosbarbero** [comment]
@robscully take a look at this new release [v1.0.2.RELEASE](https://github.com/marcosbarbero/spring-cloud-config-client-oauth2/releases/tag/v1.0.2.RELEASE) it's already on maven central, let me know if everything is set for you.

**Comment by marcosbarbero** [comment]
@robscully any update?

**Comment by robscully** [comment]
Apologies Marcos. I've been away on honeymoon the last month. I'll test this in the next couple of days and get back to you.

**Comment by marcosbarbero** [comment]
Thanks ok, take your time! When you have any update let me know
